In [ ]:
#Task 1: The Normalizer (Broadcasting & Stats)
import numpy as np
np.random.seed(0)
scores = np.random.randint(50, 101, size=(5, 3))
subject_means = scores.mean(axis=0)
centered_scores = scores - subject_means
print("Original Scores:")
print(scores)
print("\nSubject-wise Mean:")
print(subject_means)
print("\nCentered Scores:")
print(centered_scores)


Original Scores:
[[ 94  97  50]
 [ 53  53  89]
 [ 59  69  71]
 [100  86  73]
 [ 56  74  74]]

Subject-wise Mean:
[72.4 75.8 71.4]

Centered Scores:
[[ 21.6  21.2 -21.4]
 [-19.4 -22.8  17.6]
 [-13.4  -6.8  -0.4]
 [ 27.6  10.2   1.6]
 [-16.4  -1.8   2.6]]


In [ ]:
import numpy as np
scores = np.array([
    [60, 70, 80],
    [65, 75, 85],
    [70, 80, 90],
    [75, 85, 95],
    [80, 90, 100]
])

means = scores.mean(axis=0)
centered = scores - means
print("Original Scores:")
print(scores)
print("Column-wise Means:")
print(means)
print("Centered Scores:")
print(centered)


Original Scores:
[[ 60  70  80]
 [ 65  75  85]
 [ 70  80  90]
 [ 75  85  95]
 [ 80  90 100]]
Column-wise Means:
[70. 80. 90.]
Centered Scores:
[[-10. -10. -10.]
 [ -5.  -5.  -5.]
 [  0.   0.   0.]
 [  5.   5.   5.]
 [ 10.  10.  10.]]
