In [ ]:
#Task 2: The Reshaper (Array Manipulation)
import numpy as np
arr=np.arange(24)
arr_3d=arr.reshape(4,3,2)
arr_transposed=arr_3d.transpose(0,2,1)
print("Final shape:", arr_transposed.shape)
print("Final array:")
print(arr_transposed)

Final shape: (4, 2, 3)
Final array:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]


In [3]:
import numpy as np
data = np.arange(24)
data_reshaped = data.reshape(4, 3, 2)
data_transposed = data_reshaped.transpose(0, 2, 1)
print("Final shape:", data_transposed.shape)
print(data_transposed)


Final shape: (4, 2, 3)
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
