In [ ]:
#creating numpy aeeay
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [2]:
#multi dimentional array
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
#Force minimum dimention
arr2=np.array([1,2,3,4,5],ndmin=5)
print(arr2)

[[[[[1 2 3 4 5]]]]]


In [6]:
#change data type
arr3=np.array([1,2,3,4,5],dtype=bool)
print(arr3)

[ True  True  True  True  True]


In [8]:
#number of dimentions
print(arr3.ndim)
print(arr1.ndim)
print(arr2.ndim)
      

1
2
5


In [9]:
#item size
print(arr3.itemsize)
print(arr1.itemsize)
print(arr2.itemsize)

1
8
8


In [11]:
#size of each item
arr4=np.array([1,2,3,4,5],dtype=np.int64)
print(arr4.itemsize)


8


In [12]:
#shape and size
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
print(arr.size)

(2, 5)
10


In [13]:
#conerting list to array
list1=[1,2,3,4,5]
arr5=np.array(list1)
print(arr5)

[1 2 3 4 5]


In [14]:
#converting array to list
arr6=np.array([1,2,3,4,5])
list2=arr6.tolist()
print(type(list2))
print(list2)

<class 'list'>
[1, 2, 3, 4, 5]
